name: release
on:
  push:
    tags:
      - "v*"
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:all
      - run: npm run zip
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            SecretsSanta-chromium.zip
            SecretsSanta-firefox.zip
